# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
  - POWERSHELL
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - POWERSHELL_POWERSHELL                  
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: "(mountPoints/|backup/|backups/)"
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
POWERSHELL_POWERSHELL_DISABLE_ERRORS: true