trigger:
  batch: true
  branches:
    include:
    - master
    
pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  displayName: Build Modules
  jobs:
    - job: BuildModules
      steps:
        - checkout: self
        - task: PowerShell@2
          displayName: 'Build-PowershelScripts'
          inputs:
              filePath: 'Modules/Build-ALLFCModules.ps1'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(agent.builddirectory)'
            ArtifactName: 'builtSource'
            publishLocation: 'Container'
    - job: TestModules
      dependsOn: BuildModules
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'builtSource'
            targetPath: '$(Pipeline.Workspace)'
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'docker build -t bmcclure89/fc_pwsh_tests Modules/Tests/.'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'docker run --rm -it -w /tests -v ${PWD}:/tests bmcclure89/fc_pwsh_tests'
    - job: PackageModules
      dependsOn: TestModules
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'builtSource'
            targetPath: '$(Pipeline.Workspace)'
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec: '5.x'
        - task: NuGetCommand@2
          displayName: 'NuGet pack'
          inputs:
            command: pack
            packagesToPack: '**\*.nuspec'
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '*'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'builtSource'
            publishLocation: 'Container'